name: Expose Pythons
description: Exposes Pythons on the PATH.
runs:
  using: composite
  steps:
    - name: Expose Pythons
      run: |
        if [[ "$(uname -s)" == "Darwin" ]]; then
          toolcache="/Users/runner/hostedtoolcache"
        else
          toolcache="/opt/hostedtoolcache"
        fi

        echo "::group::Exposing Pythons"
        for python_location in ${toolcache}/Python/*/x64; do
          # N.B.: Python 2.7 prints the version to stderr so we re-direct to get output all on one
          # line in that case.
          python_bin_dir="${python_location}/bin"
          echo "Exposing ${python_bin_dir}: $(${python_bin_dir}/python --version 2>&1)"
          PATH="${PATH}:${python_bin_dir}"

          python_lib_dir="${python_location}/lib"
          LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${python_lib_dir}"
        done
        echo "::endgroup::"

        echo "PATH=${PATH}" >> $GITHUB_ENV

        # The actions/setup-python@v2 action sets up LD_LIBRARY_PATH on Linux and so we do too to
        # avoid issues like: https://github.com/pantsbuild/pex/issues/1391.
        if [[ "$(uname -s)" == "Linux" ]]; then
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        fi
      shell: bash
